contactEmail: info@capital49.com
linkedin: https://www.linkedin.com/company/capital-49/
mapUrl: https://maps.app.goo.gl/CjVBPAzM77GEDYEU7
latitude: 37.7916
longitude: -122.393
footerNote: Est. 2021 — San Francisco
